import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Menu from "../components/Menu";
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      {/* <Header> */}
      <div className="flex flex-col place-items-center py-44 space-y-3">
        <h1 className="text-5xl font-bold">Ayo mulai voting</h1>
        <h2 className="text-lg bg-zinc-100 px-3 py-1">
          Web Voting No.1 Di Indonesia
        </h2>
        <Image
          alt="Header"
          src={"/assets/header.svg"}
          width={274}
          height={243}
        />
        <div className="space-x-10">
          <Button text="Buat Vote Baru" className="font-bold" />
          <Button text="Ikutan Vote" type="secondary" className="font-bold" />
        </div>
      </div>
      {/* </Header> */}
    </div>
  );
};

export default Home;
